apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: flask-blog
  labels:
      type: blog
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-app
        type: blog
    spec:
      tolerations:
      - key: kubernetes.io/hostname
        operator: Equal
        value: kind-control-plane
        effect: NoSchedule
      containers:
      - name: flask-app
        image: blog:v1.0.0
        # https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef:
                key: mysql_database_port
                name: flask-data
          - name: MYSQL_DB_NAME
            valueFrom:
              configMapKeyRef:
                key: mysql_database_name
                name: flask-data
          - name: MYSQL_HOSTNAME
            valueFrom:
              configMapKeyRef:
                key: mysql_headless_service_hostname
                name: flask-data
          - name: MYSQL_FLASK_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: mysql-flask-auth
          - name: MYSQL_FLASK_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysql-flask-auth
          - name: FLASK_APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: flask_app_secret_key
                name: flask-secret-key
        ports:
        - containerPort: 5000
