---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: flask-app
spec:
  selector:
    type: blog
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30423
