apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-blog.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-blog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: {{ .Values.flaskAppReplicasNumber }}
  template:
    metadata:
      labels:
        {{- include "flask-blog.labels" . | nindent 8 }}
    spec:
      tolerations:
        - key: kubernetes.io/hostname
          operator: Equal
          value: kind-control-plane
          effect: NoSchedule
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "flask-blog.getImage" . }}
          # https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
          imagePullPolicy: {{ .Values.flaskImage.pullPolicy }}
          resources:
            requests:
              {{- .Values.flaskResources.requests | toYaml | nindent 14 }}
            limits:
              {{- .Values.flaskResources.limits | toYaml | nindent 14 }}
          env:
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: mysql_database_port
                  name: {{ include "flask-blog.name" . }}-data-configmap
            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: mysql_database_name
                  name: {{ include "flask-blog.name" . }}-data-configmap
            - name: MYSQL_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: mysql_headless_service_hostname
                  name: {{ include "flask-blog.name" . }}-data-configmap
            - name: MYSQL_FLASK_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ include "flask-blog.name" . }}-user-secret
            - name: MYSQL_FLASK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ include "flask-blog.name" . }}-user-secret
            - name: FLASK_APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: flask_app_secret_key
                  name: {{ include "flask-blog.name" . }}-flask-key-secret
          ports:
            - containerPort: {{ .Values.flaskAppContainerPort }}
