---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: flask-app
spec:
  ports:
    - port: 3306
  selector:
    db: mysql-instance
  clusterIP: None
