---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-chart.labels" . | nindent 4 }}
data:
  mysql_database_name: {{ .Values.database.name }}
  mysql_database_port: {{ .Values.database.port }}
  # <statefulset pod name>.<headless service name>.<namespace>.svc.cluster.local
  # Why use headless service for stateful set?
  # We get stable and consistent DNS naming
  # re-created pod receives same unique identifier as before
  # No loadbalancing - single master db, rest used as read replicas
  mysql_headless_service_hostname: {{ .Chart.Name }}-statefulset-0.{{ .Chart.Name }}-mysql-service.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-mysql-configmap
  namespace: {{ .Release.Namespace }}
data:
  schema.sql: |{{ range .Files.Lines "k8s-helm-mysql-init.sql" }}
    {{ . | replace "flaskr" $.Values.database.name }}{{ end }}
