---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-daemon-set
  namespace: logging
  labels:
    department: fluentd-logging
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
      department: fluentd-logging
  template:
    metadata:
      labels:
        app: flask-app
        department: fluentd-logging
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: kubernetes.io/hostname
        operator: Equal
        value: kind-control-plane
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name:  FLUENT_ELASTICSEARCH_HOST
            valueFrom:
              configMapKeyRef:
                key: elasticsearch_host
                name: fluentd-configmap
          - name:  FLUENT_ELASTICSEARCH_PORT
            valueFrom:
              configMapKeyRef:
                key: elasticsearch_port
                name: fluentd-configmap
          - name: FLUENT_ELASTICSEARCH_SCHEME
            valueFrom:
              configMapKeyRef:
                key: elasticsearch_scheme
                name: fluentd-configmap
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-configmap
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers