apiVersion: v1
kind: Secret
metadata:
  name: mysql-superuser-auth
  namespace: flask-blog
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-flask-auth
  namespace: flask-blog
type: kubernetes.io/basic-auth
stringData:
  username: piotr
  password: piotr
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret-key
  namespace: flask-blog
type: Opaque
data:
  flask_app_secret_key: 6cFKoOLSEeOZX5y8yQNqk5WWPBMW
