---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "efk.fluentdName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "efk.fluentdName" . }}
rules:
  {{- .Values.fluentd.serviceAccountRules | toYaml | nindent 2 }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "efk.fluentdName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "efk.fluentdName" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "efk.fluentdName" . }}
    namespace: {{ .Release.Namespace }}
