---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "efk.fluentdName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "efk.fluentd.labels" . | nindent 4 }}
data:
  {{- .Values.fluentd.config | toYaml | nindent 2 }}
  {{- tpl (.Files.Glob "*fluent*.conf").AsConfig . | nindent 2 }}
