---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "efk.fluentdName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "efk.fluentd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "efk.fluentd.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "efk.fluentd.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "efk.fluentdName" . }}
      serviceAccountName: {{ include "efk.fluentdName" . }}
      tolerations:
        - key: kubernetes.io/hostname
          operator: Equal
          value: kind-control-plane
          effect: NoSchedule
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "efk.fluentd.getImage" . }}
          imagePullPolicy: {{ .Values.fluentd.image.pullPolicy}}
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FLUENT_ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  key: elasticsearch_host
                  name: {{ include "efk.fluentdName" . }}
            - name: FLUENT_ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  key: elasticsearch_port
                  name: {{ include "efk.fluentdName" . }}
            - name: FLUENT_ELASTICSEARCH_SCHEME
              valueFrom:
                configMapKeyRef:
                  key: elasticsearch_scheme
                  name: {{ include "efk.fluentdName" . }}
          resources:
            requests:
              {{- .Values.fluentd.resources.requests | toYaml | nindent 14 }}
            limits:
              {{- .Values.fluentd.resources.limits | toYaml | nindent 14 }}
          volumeMounts:
            {{- .Values.fluentd.volumeMounts | toYaml | nindent 12 }}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: fluentd-config
          configMap:
            name: {{ include "efk.fluentdName" . }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
