---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "efk.kibanaName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "efk.kibana.labels" . | nindent 4 }}
data:
  kibana.yml: |
    {{- .Values.kibana.config | toYaml | nindent 4 }}
  elasticsearch_hosts: '["http://{{ include "efk.elasticsearchName" . }}:{{ .Values.elasticsearch.options.port }}"]'
