# Default values for flask-blog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # Name of the MySQL DB used for Flask Blog App
  mySqlDatabaseName: flaskr

  # Port on which the MySQL is listening for connections
  mySqlDatabasePort: "3306"

# Secret key for Flask App, which will be base64 encoded
flaskAppSecretKey: "my-super-secret-flask-key"

# (Optional) Custom name of the chart
nameOverride:

# (Optional) Custom full name of the chart. Truncated at 64 chars.
fullnameOverride:

# Number of Flask Blog App instances (replicas)
flaskAppReplicasNumber: 2

# Configuration dictionary for retrieving flask image
flaskImage:
  repository: blog
  tag: v1.0.0
  digest:
  pullPolicy: Never

# Configuration dictionary for specifying Flask Blog App resource quotas
flaskResources:
  limits:
    memory: "512Mi"
    cpu: "1000m"
  requests:
    memory: "256Mi"
    cpu: "500m"

# Port on which Flask Blog App is listening for connections
flaskAppContainerPort: 5000
