---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootUsername: {{ .Values.rootDatabaseUsername | quote | lower }}
  rootPassword: {{ .Values.rootDatabasePassword | quote | lower }}
  appUsername: {{ .Values.flaskDatabaseUsername | quote | lower }}
  appPassword: {{ .Values.flaskDatabasePassword | quote | lower }}
