---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.global.mySqlDatabasePort }}
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  clusterIP: None
